#!/bin/bash
# This is a wrapper for gsudo intended to be used from WSL. 
# Ensures WSLENV is set before calling gsudo, to let gsudo know the WSL context.
# Also allows `gsudo` usage, no need for `gsudo.exe`
# Harmless on git-bash/cygwin.
# You can also use 'gsudo.exe [command]' syntax (to avoids this wrapper),

export WSLENV=WSL_DISTRO_NAME:USER:$WSLENV
gsudo.exe "$@"
