name: Winget manual dispatch

on:
  workflow_dispatch: 

jobs:
  publishToWinGet:
    name: Push to Winget
    if: github.repository == 'gerardog/gsudo'
    runs-on: windows-latest
    permissions:
      contents: write
    environment:
      name: release-chocolatey
    steps:
    - name: WinGet Releaser
      uses: vedantmgoyal9/winget-releaser@main
      with: 
        token: ${{ secrets.WINGET_RELEASER_TOKEN }}
        identifier: gerardog.gsudo
        installers-regex: '\.msi$' # Only .msi files
